baseURL = 'https://github.com/yugr/yugr.github.io/recovering-teamlead'
languageCode = 'en-us'
title = 'Recovering Teamlead Blog'
author = 'Yuri "yugr" Gribov'
copyright = '(c) yugr'

theme = 'archie'

enableRobotsTXT = true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/yugr"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
