name: Publish to GH pages
on:
  push:
    branches:
      - main
  pull_request:

env:
  BLOG_NAME: recovering-teamlead

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v4
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          cd $BLOG_NAME
          hugo --minify

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd $GITHUB_WORKSPACE/built-site
          git rm -r $BLOG_NAME
          mkdir -p $BLOG_NAME
          cp -r $GITHUB_WORKSPACE/$BLOG_NAME/public/* $BLOG_NAME
          git add .
          git config user.name 'Yuri Gribov'
          git config user.email 'tetra2005@gmail.com'
          git commit -m'Update site.'
          git push
